### ISSUE TITLE
Issue with adding required plugins

### ISSUE THREAD

**Issue by FearlessNite345** [WhitigolSoftware/wLauncher#1] opened 2024-06-17 22:38 UTC
So when i try to add a plugin to that and hit the button to make the server file it just says there are no required plugins and im not sure how to fix it

**Comment by whitigol** [comment] 2024-07-17 02:38
Sorry for the very delayed reply, I've been quite busy over the past couple months with quite a few different things.

I'm not sure what you mean exactly? Could you provide more details, and possibly steps to reproduce?

Thanks!

**Comment by FearlessNite345** [comment] 2024-07-17 03:05
If i am setting up a server and add a required plugin once the server has been made it then shows there are no required plugins not sure if im doing something wrong or not and your fine on the delay

**Comment by whitigol** [comment] 2024-07-17 03:06
Could you possibly send me your exported profile? I'll check to see if the format might be getting messed up for some reason.

**Comment by FearlessNite345** [comment] 2024-07-19 20:54
well i tried to replicate it on v1.1.2 and maybe im adding plugins wrong but it tells me to fill out all the fields but i did and wont add it im trying to add the sirensetting limit adjuster

**Comment by whitigol** [comment] 2024-07-19 21:29
Could you send a video reproduction?

**Comment by FearlessNite345** [comment] 2024-07-19 21:39
Sure this is a short video of setting up a new server https://youtu.be/8U22wDA9sbw

**Comment by whitigol** [comment] 2024-07-19 22:52
Hmm, I don't appear to be able to reproduce this exact issue, however, there is an issue with setting required plugins that I did find, and that is part of the issue I'm seeing in your preview video.

Currently, even when adding required plugins, it doesn't seem to be adding to the list once the profile is created and saved, and I've implemented a fix that will resolve this in the next update of the launcher.

The initial issue presented in your video is throwing an error saying `Please fill out all required fields`, which can only be thrown as a result of either the plugin file name, or download URL being left blank when clicking "Add" on the Add Plugin window. After looking into this, this appears to somehow get thrown if the fields are entered in the reverse order (starting from the bottom). I'm not too sure why this is the case, because after testing both fields, they are detecting any change and setting the internal value in order to submit the form, however it's for some reason not working as intended.

My recommendation for now, until I'm able to resolve that, would be to enter the required plugin form starting at the top, rather than the bottom. I will be sure to look into this in a future update.

I hope this clears some things up for you, please message back if this helped the issue you're currently having!

**Comment by FearlessNite345** [comment] 2024-07-20 01:40
ok i see and yea after trying to do it top to bottom it worked just once created it wasn't in the list as you stated

**Comment by whitigol** [comment] 2024-07-20 03:31
The latest version is released and should fix that 🙂

**Comment by FearlessNite345** [comment] 2024-07-20 03:43
Awesome i appericiate the help also wanted to ask what kind of download link needs to be for the plugins cause i tried a lspdfr link and it fails to download so wasnt sure tbh

**Comment by whitigol** [comment] 2024-07-20 03:47
It needs to be a direct file download

**Comment by FearlessNite345** [comment] 2024-07-20 03:48
So direct to the .asi or can it be in a zip file just making sure i understand that part

**Comment by whitigol** [comment] 2024-07-20 03:48
You're welcome to use this:
```
https://github.com/WhitigolScripts/bdrp-launcher-release/releases/download/0.0.0-dev.0/SirenSetting_Limit_Adjuster.asi
```

**Comment by whitigol** [comment] 2024-07-20 03:48
Must be the `.asi` file

**Comment by FearlessNite345** [comment] 2024-07-20 03:50
understood thank you this app has been very helpful to me

**Comment by whitigol** [comment] 2024-07-20 03:51
Glad to hear it!

**Comment by whitigol** [comment] 2024-07-20 03:51
Enjoy the new themes 🙂

**Comment by FearlessNite345** [comment] 2024-07-20 03:52
Love the themes keep up the work man. Have a nice night

**Comment by whitigol** [comment] 2024-07-20 06:21
We'll leave this open for now until the other bug is resolved 🙂

**Comment by FearlessNite345** [comment] 2024-07-20 06:22
No problem

**Comment by whitigol** [comment] 2024-07-24 05:18
I'm closing this issue for the time being. I plan to develop a more efficient method for implementing plugin requirements for individual profiles. However, this enhancement might take some time. In the meantime, you'll need to continue entering the fields sequentially from top to bottom. Thank you for your patience.

**Closed as completed by whitigol** 2024-07-24 05:18 UTC
Labels: bug, question
